const fs = require("fs");
const path = require("path");
const f = path.join(__dirname,"..","data","builtin-links.json");
const M={b:"browser",d:"development",r:"runtime",D:"database",g:"design",c:"communication",m:"media",s:"security",u:"utility",p:"productivity",G:"game",o:"other"};
function E(n,a,o,dl,c){return{software_name:n,aliases:a.map(x=>x.toLowerCase()),official_url:o,direct_download_url:dl||"",category:M[c]||c,verified:true}}
const entries=JSON.parse(fs.readFileSync(f,"utf-8"));
const seen=new Set(entries.map(e=>e.software_name));
let a=0;
function ad(arr){for(const e of arr){if(!seen.has(e.software_name)){seen.add(e.software_name);entries.push(e);a++;}}}
ad([
E("Opera",["opera","opera browser"],"https://www.opera.com/download","https://net.geo.opera.com/opera/stable/windows","b"),
E("Vivaldi",["vivaldi","vivaldi browser"],"https://vivaldi.com/download/","","b"),
E("Tor Browser",["tor","tor browser","torbrowser"],"https://www.torproject.org/download/","","b"),
E("Yandex Browser",["yandex","yandex browser"],"https://browser.yandex.com/","","b"),
E("Arc Browser",["arc","arc browser"],"https://arc.net/","","b"),
E("Maxthon",["maxthon","maxthon browser"],"https://www.maxthon.com/","","b"),
E("Pale Moon",["palemoon","pale moon"],"https://www.palemoon.org/","","b"),
E("Waterfox",["waterfox"],"https://www.waterfox.net/","","b"),
E("Cent Browser",["cent","cent browser"],"https://www.centbrowser.com/","","b"),
E("Kiwi Browser",["kiwi","kiwi browser"],"https://kiwibrowser.com/","","b"),
E("Safari",["safari"],"https://www.apple.com/safari/","","b"),
E("UC Browser",["uc","uc browser"],"https://www.ucweb.com/","","b"),
E("Slimjet",["slimjet"],"https://www.slimjet.com/","","b"),
E("Comodo Dragon",["comodo dragon","dragon"],"https://www.comodo.com/home/browsers-toolbars/browser.php","","b"),
E("Naver Whale",["whale","naver whale"],"https://whale.naver.com/","","b"),
E("SRWare Iron",["iron","srware iron"],"https://www.srware.net/iron/","","b"),
E("IntelliJ IDEA Ultimate",["intellij ultimate","idea ultimate"],"https://www.jetbrains.com/idea/download/","","d"),
E("PyCharm Community",["pycharm","pycharm community"],"https://www.jetbrains.com/pycharm/download/","","d"),
E("PyCharm Professional",["pycharm pro","pycharm professional"],"https://www.jetbrains.com/pycharm/download/","","d"),
E("WebStorm",["webstorm"],"https://www.jetbrains.com/webstorm/download/","","d"),
E("GoLand",["goland"],"https://www.jetbrains.com/go/download/","","d"),
E("Android Studio",["android studio","androidstudio"],"https://developer.android.com/studio","","d"),
E("Eclipse IDE",["eclipse","eclipse ide"],"https://eclipseide.org/","","d"),
E("NetBeans",["netbeans","apache netbeans"],"https://netbeans.apache.org/","","d"),
E("CLion",["clion"],"https://www.jetbrains.com/clion/download/","","d"),
E("Rider",["rider","jetbrains rider"],"https://www.jetbrains.com/rider/download/","","d"),
E("RubyMine",["rubymine"],"https://www.jetbrains.com/ruby/download/","","d"),
E("PhpStorm",["phpstorm"],"https://www.jetbrains.com/phpstorm/download/","","d"),
E("VS 2022 Community",["vs2022 community","vs community"],"https://visualstudio.microsoft.com/vs/community/","","d"),
E("VS 2022 Professional",["vs2022 pro","vs professional"],"https://visualstudio.microsoft.com/vs/professional/","","d"),
E("VS 2022 Enterprise",["vs2022 enterprise","vs enterprise"],"https://visualstudio.microsoft.com/vs/enterprise/","","d"),
E("Visual Studio 2019",["vs2019"],"https://visualstudio.microsoft.com/vs/older-downloads/","","d"),
E("VS Code Insiders",["vscode insiders","code insiders"],"https://code.visualstudio.com/insiders/","","d"),
E("Atom",["atom"],"https://atom-editor.cc/","","d"),
E("Vim",["vim","gvim"],"https://www.vim.org/download.php","","d"),
E("NeoVim",["neovim","nvim"],"https://neovim.io/","","d"),
E("Emacs",["emacs","gnu emacs"],"https://www.gnu.org/software/emacs/","","d"),
E("GitHub Desktop",["github desktop","githubdesktop"],"https://desktop.github.com/","","d"),
E("SourceTree",["sourcetree","atlassian sourcetree"],"https://www.sourcetreeapp.com/","","d"),
E("GitKraken",["gitkraken"],"https://www.gitkraken.com/","","d"),
E("Insomnia",["insomnia"],"https://insomnia.rest/download","","d"),
E("Jupyter",["jupyter","jupyter notebook"],"https://jupyter.org/","","d"),
E("Anaconda",["anaconda"],"https://www.anaconda.com/download","","d"),
E("CMake",["cmake"],"https://cmake.org/download/","","d"),
E("Gradle",["gradle"],"https://gradle.org/install/","","d"),
E("Maven",["maven","apache maven"],"https://maven.apache.org/download.cgi","","d"),
E("Vagrant",["vagrant","hashicorp vagrant"],"https://www.vagrantup.com/downloads","","d"),
E("VirtualBox",["virtualbox","oracle vm virtualbox"],"https://www.virtualbox.org/wiki/Downloads","","d"),
E("VMware Workstation Pro",["vmware","vmware workstation"],"https://www.vmware.com/products/workstation-pro.html","","d"),
E("WSL",["wsl","wsl2","windows subsystem for linux"],"https://learn.microsoft.com/en-us/windows/wsl/","","d"),
E("yarn",["yarn","yarnpkg"],"https://yarnpkg.com/","","d"),
E("pnpm",["pnpm"],"https://pnpm.io/installation","","d"),
E("bun",["bun"],"https://bun.sh/","","d"),
E("Deno",["deno"],"https://deno.land/","","d"),
E("Kubernetes",["kubernetes","k8s"],"https://kubernetes.io/","","d"),
E("Minikube",["minikube"],"https://minikube.sigs.k8s.io/docs/","","d"),
E("Helm",["helm"],"https://helm.sh/","","d"),
E("Terraform",["terraform","hashicorp terraform"],"https://www.terraform.io/downloads","","d"),
E("Ansible",["ansible"],"https://www.ansible.com/","","d"),
E("Jenkins",["jenkins"],"https://www.jenkins.io/download/","","d"),
E("TeamCity",["teamcity","jetbrains teamcity"],"https://www.jetbrains.com/teamcity/download/","","d"),
E("Octopus Deploy",["octopus deploy","octopus"],"https://octopus.com/downloads","","d"),
E("FileZilla",["filezilla"],"https://filezilla-project.org/","","d"),
E("WinSCP",["winscp"],"https://winscp.net/","","d"),
E("PuTTY",["putty"],"https://www.putty.org/","","d"),
E("OpenSSH",["openssh","ssh"],"https://www.openssh.com/","","d"),
E("Wireshark",["wireshark"],"https://www.wireshark.org/download.html","","d"),
E("Fiddler Everywhere",["fiddler","fiddler everywhere"],"https://www.telerik.com/download/fiddler-everywhere","","d"),
E("Charles Proxy",["charles proxy","charles"],"https://www.charlesproxy.com/download/","","d"),
E("curl",["curl"],"https://curl.se/windows/","","d"),
E("wget",["wget","gnu wget"],"https://eternallybored.org/misc/wget/","","d"),
E("TortoiseGit",["tortoisegit"],"https://tortoisegit.org/","","d"),
E("TortoiseSVN",["tortoisesvn"],"https://tortoisesvn.net/","","d"),
E("Make",["make","gnu make"],"https://www.gnu.org/software/make/","","d"),
E("Redis Insight",["redis insight","redisinsight"],"https://redis.com/redis-enterprise/redis-insight/","","d"),
E("Azure Data Studio",["azure data studio","ads"],"https://learn.microsoft.com/en-us/azure-data-studio/download","","d"),
E("Oracle JDK",["oracle jdk","oracle java"],"https://www.oracle.com/java/technologies/downloads/","","r"),
E("Java JRE",["jre","java runtime"],"https://www.java.com/download/","","r"),
E("Rust",["rust","rustc"],"https://www.rust-lang.org/tools/install","","r"),
E(".NET SDK",["dotnet","dotnet sdk",".net sdk"],"https://dotnet.microsoft.com/download","","r"),
E(".NET Runtime",[".net runtime","dotnet runtime"],"https://dotnet.microsoft.com/en-us/download/dotnet","","r"),
E(".NET Framework 4.8",["dotnet framework",".net framework"],"https://dotnet.microsoft.com/en-us/download/dotnet-framework","","r"),
E("Ruby",["ruby"],"https://rubyinstaller.org/","","r"),
E("PHP",["php"],"https://windows.php.net/download/","","r"),
E("Perl",["perl","strawberry perl"],"https://strawberryperl.com/","","r"),
E("Lua",["lua"],"https://lua.org/","","r"),
E("R Language",["r","r language"],"https://cran.r-project.org/bin/windows/base/","","r"),
E("Julia",["julia"],"https://julialang.org/downloads/","","r"),
E("Erlang",["erlang"],"https://www.erlang.org/downloads","","r"),
E("Elixir",["elixir"],"https://elixir-lang.org/install.html","","r"),
E("Haskell",["haskell","ghc"],"https://www.haskell.org/downloads/","","r"),
E("Scala",["scala"],"https://www.scala-lang.org/download/","","r"),
E("Kotlin",["kotlin"],"https://kotlinlang.org/","","r"),
E("Dart",["dart"],"https://dart.dev/get-dart","","r"),
E("Flutter",["flutter"],"https://docs.flutter.dev/get-started/install/windows","","r"),
E("CUDA Toolkit",["cuda","nvidia cuda"],"https://developer.nvidia.com/cuda-downloads","","r"),
E("PowerShell 7",["powershell","pwsh"],"https://learn.microsoft.com/en-us/powershell/","","r"),
E("MinGW-w64",["mingw","mingw-w64"],"https://www.mingw-w64.org/","","r"),
E("MSYS2",["msys2"],"https://www.msys2.org/","","r"),
E("LLVM/Clang",["clang","llvm"],"https://releases.llvm.org/","","r"),
E("MySQL",["mysql server","mysql community"],"https://dev.mysql.com/downloads/mysql/","","D"),
E("pgAdmin",["pgadmin","pgadmin4"],"https://www.pgadmin.org/download/","","D"),
E("Navicat Premium",["navicat","navicat premium"],"https://www.navicat.com/en/download/navicat-premium","","D"),
E("SQLite",["sqlite"],"https://www.sqlite.org/download.html","","D"),
E("SQLiteStudio",["sqlitestudio"],"https://sqlitestudio.pl/","","D"),
E("SQL Server",["sql server","mssql"],"https://www.microsoft.com/en-us/sql-server/sql-server-downloads","","D"),
E("SSMS",["ssms","sql server management studio"],"https://learn.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms","","D"),
E("Oracle Database",["oracle db","oracle database"],"https://www.oracle.com/database/technologies/","","D"),
E("Oracle SQL Developer",["oracle sql developer","sqldeveloper"],"https://www.oracle.com/database/sqldeveloper/","","D"),
E("MongoDB Community Server",["mongodb","mongo"],"https://www.mongodb.com/try/download/community","","D"),
E("MongoDB Compass",["mongodb compass"],"https://www.mongodb.com/products/compass","","D"),
E("Redis",["redis"],"https://redis.io/download/","","D"),
E("Redis Desktop Manager",["rdm","redis desktop manager"],"https://redisdesktop.com/","","D"),
E("Memurai",["memurai"],"https://www.memurai.com/","","D"),
E("Cassandra",["cassandra"],"https://cassandra.apache.org/","","D"),
E("Neo4j Desktop",["neo4j"],"https://neo4j.com/download/","","D"),
E("CouchDB",["couchdb"],"https://couchdb.apache.org/","","D"),
E("MariaDB",["mariadb"],"https://mariadb.org/download/","","D"),
E("Firebird",["firebird"],"https://firebirdsql.org/","","D"),
E("Supabase CLI",["supabase"],"https://supabase.com/docs/guides/cli","","D"),
E("DbVisualizer",["dbvisualizer"],"https://www.dbvis.com/download/","","D"),
E("TablePlus",["tableplus"],"https://tableplus.com/download","","D"),
E("Adobe Photoshop",["photoshop","ps","adobe photoshop"],"https://www.adobe.com/products/photoshop.html","","g"),
E("Adobe Illustrator",["illustrator","ai"],"https://www.adobe.com/products/illustrator.html","","g"),
E("Adobe InDesign",["indesign"],"https://www.adobe.com/products/indesign.html","","g"),
E("Adobe After Effects",["after effects","ae"],"https://www.adobe.com/products/aftereffects.html","","g"),
E("Adobe Premiere Pro",["premiere pro","premiere"],"https://www.adobe.com/products/premiere.html","","g"),
E("Adobe Lightroom",["lightroom"],"https://www.adobe.com/products/photoshop-lightroom.html","","g"),
E("Sketch",["sketch"],"https://www.sketch.com/","","g"),
E("Krita",["krita"],"https://krita.org/en/download/","","g"),
E("Paint.NET",["paint.net","paintnet"],"https://www.getpaint.net/","","g"),
E("Affinity Photo",["affinity photo"],"https://affinity.serif.com/en-us/photo/","","g"),
E("Affinity Designer",["affinity designer"],"https://affinity.serif.com/en-us/designer/","","g"),
E("CorelDraw",["coreldraw"],"https://www.coreldraw.com/","","g"),
E("AutoCAD",["autocad"],"https://www.autodesk.com/products/autocad/","","g"),
E("Fusion 360",["fusion 360","fusion360"],"https://www.autodesk.com/products/fusion-360/","","g"),
E("SolidWorks",["solidworks"],"https://www.solidworks.com/","","g"),
E("FreeCAD",["freecad"],"https://www.freecad.org/downloads.php","","g"),
E("DaVinci Resolve",["davinci resolve","davinci"],"https://www.blackmagicdesign.com/products/davinciresolve/","","g"),
E("Canva",["canva"],"https://www.canva.com/download/","","g"),
E("Aseprite",["aseprite"],"https://www.aseprite.org/","","g"),
E("Maya",["maya","autodesk maya"],"https://www.autodesk.com/products/maya/","","g"),
E("3ds Max",["3ds max","3d max"],"https://www.autodesk.com/products/3ds-max/","","g"),
E("Cinema 4D",["cinema 4d","c4d"],"https://www.maxon.net/en/cinema-4d","","g"),
E("ZBrush",["zbrush"],"https://www.maxon.net/en/zbrush","","g"),
E("Procreate",["procreate"],"https://procreate.com/","","g"),
E("WeChat",["wechat","weixin"],"https://pc.weixin.qq.com/","","c"),
E("QQ",["qq"],"https://im.qq.com/pcqq/","","c"),
E("TIM",["tim"],"https://office.qq.com/","","c"),
E("Microsoft Teams",["teams","microsoft teams"],"https://www.microsoft.com/en-us/microsoft-teams/download-app","","c"),
E("DingTalk",["dingtalk","dingding"],"https://www.dingtalk.com/en","","c"),
E("Feishu",["feishu","lark"],"https://www.feishu.cn/download","","c"),
E("WhatsApp",["whatsapp"],"https://www.whatsapp.com/download","","c"),
E("Skype",["skype"],"https://www.skype.com/en/get-skype/","","c"),
E("Signal",["signal"],"https://signal.org/download/","","c"),
E("Viber",["viber"],"https://www.viber.com/download/","","c"),
E("Line",["line"],"https://line.me/en-US/download","","c"),
E("KakaoTalk",["kakaotalk"],"https://www.kakaocorp.com/page/service/service/KakaoTalk","","c"),
E("Messenger",["messenger"],"https://www.messenger.com/desktop","","c"),
E("Element",["element","matrix"],"https://element.io/download","","c"),
E("HexChat",["hexchat","irc"],"https://hexchat.github.io/","","c"),
E("Trello",["trello"],"https://trello.com/platforms","","c"),
E("Asana",["asana"],"https://asana.com/download","","c"),
E("Notion",["notion"],"https://www.notion.so/desktop","","c"),
E("Twist",["twist"],"https://twist.com/download","","c"),
E("Mattermost",["mattermost"],"https://mattermost.com/download/","","c"),
E("Rocket.Chat",["rocket.chat","rocketchat"],"https://www.rocket.chat/download","","c"),
E("Google Meet",["google meet"],"https://meet.google.com/","","c"),
E("Cisco Webex",["webex","cisco webex"],"https://www.webex.com/downloads.html","","c"),
E("Zoho Cliq",["zoho cliq","cliq"],"https://www.zoho.com/cliq/download/","","c"),
E("Tencent Meeting",["tencent meeting","voov meeting"],"https://voovmeeting.com/download-center.html","","c"),
E("MPC-HC",["mpc-hc","mpc hc"],"https://mpc-hc.org/","","m"),
E("MPC-BE",["mpc-be","mpc be"],"https://mpcbe.sourceforge.io/","","m"),
E("KMPlayer",["kmplayer"],"https://www.kmplayer.com/","","m"),
E("GOM Player",["gom player"],"https://www.gomlab.com/gomplayer-media-player/","","m"),
E("foobar2000",["foobar2000","foobar"],"https://www.foobar2000.org/download","","m"),
E("AIMP",["aimp"],"https://www.aimp.ru/","","m"),
E("MusicBee",["musicbee"],"https://getmusicbee.com/","","m"),
E("XSplit",["xsplit"],"https://www.xsplit.com/download","","m"),
E("Streamlabs Desktop",["streamlabs"],"https://streamlabs.com/","","m"),
E("Bandicam",["bandicam"],"https://www.bandicam.com/downloads/","","m"),
E("Audacity",["audacity"],"https://www.audacityteam.org/download/","","m"),
E("Adobe Audition",["audition","adobe audition"],"https://www.adobe.com/products/audition.html","","m"),
E("Cubase",["cubase"],"https://www.steinberg.net/cubase/","","m"),
E("FL Studio",["fl studio"],"https://www.image-line.com/fl-studio-download/","","m"),
E("Ableton Live",["ableton live"],"https://www.ableton.com/en/live/","","m"),
E("HandBrake",["handbrake"],"https://handbrake.fr/downloads.php","","m"),
E("FFmpeg",["ffmpeg"],"https://ffmpeg.org/download.html","","m"),
E("LosslessCut",["losslesscut"],"https://github.com/mifi/lossless-cut","","m"),
E("Shotcut",["shotcut"],"https://shotcut.org/download/","","m"),
E("Kdenlive",["kdenlive"],"https://kdenlive.org/en/download/","","m"),
E("OpenShot",["openshot"],"https://www.openshot.org/download/","","m"),
E("mpv",["mpv"],"https://mpv.io/installation/","","m"),
E("SMPlayer",["smplayer"],"https://www.smplayer.info/downloads/","","m"),
E("VSDC Video Editor",["vsdc"],"https://www.videosoftdev.com/free-video-editor","","m"),
E("Ocenaudio",["ocenaudio"],"https://www.ocenaudio.com/en/download","","m"),
E("REAPER",["reaper"],"https://www.reaper.fm/download.php","","m"),
E("LMMS",["lmms"],"https://lmms.io/download/","","m"),
E("360 Total Security",["360 total security"],"https://www.360totalsecurity.com/","","s"),
E("360 Antivirus",["360 antivirus"],"https://www.360totalsecurity.com/en/antivirus/","","s"),
E("Huorong",["huorong"],"https://www.huorong.cn/","","s"),
E("ESET NOD32",["eset","nod32"],"https://www.eset.com/us/home/antivirus/","","s"),
E("Avast",["avast"],"https://www.avast.com/download-antivirus","","s"),
E("AVG",["avg"],"https://www.avg.com/en-us/download-antivirus","","s"),
E("Avira",["avira"],"https://www.avira.com/en/download-free-antivirus","","s"),
E("Norton",["norton"],"https://www.norton.com/downloads","","s"),
E("McAfee",["mcafee"],"https://www.mcafee.com/downloads/antivirus.aspx","","s"),
E("Comodo Antivirus",["comodo"],"https://www.comodo.com/home/download/download.php","","s"),
E("ZoneAlarm",["zonealarm"],"https://www.zonealarm.com/software/firewall/","","s"),
E("GlassWire",["glasswire"],"https://www.glasswire.com/download/","","s"),
E("WireGuard",["wireguard"],"https://www.wireguard.com/install/","","s"),
E("OpenVPN",["openvpn"],"https://openvpn.net/download-open-vpn/","","s"),
E("ProtonVPN",["protonvpn"],"https://protonvpn.com/download/","","s"),
E("Cloudflare WARP",["cloudflare warp","warp"],"https://1.1.1.1/","","s"),
E("1Password",["1password"],"https://1password.com/downloads/windows/","","s"),
E("Bitwarden",["bitwarden"],"https://bitwarden.com/download/","","s"),
E("KeePass",["keepass"],"https://keepass.info/download.html","","s"),
E("KeePassXC",["keepassxc"],"https://keepassxc.org/download/","","s"),
E("VeraCrypt",["veracrypt"],"https://www.veracrypt.fr/en/Downloads.html","","s"),
E("NordVPN",["nordvpn"],"https://nordvpn.com/download/","","s"),
E("ExpressVPN",["expressvpn"],"https://www.expressvpn.com/download","","s"),
E("AdGuard",["adguard"],"https://adguard.com/en/download.html","","s"),
E("uBlock Origin",["ublock origin","ublock"],"https://ublockorigin.com/","","s"),
E("WinRAR",["winrar","rar"],"https://www.win-rar.com/download.html","","u"),
E("Bandizip",["bandizip"],"https://www.bandisoft.com/bandizip/","","u"),
E("PeaZip",["peazip"],"https://peazip.github.io/","","u"),
E("Snipaste",["snipaste"],"https://www.snipaste.com/","","u"),
E("Greenshot",["greenshot"],"https://getgreenshot.org/download/","","u"),
E("Lightshot",["lightshot"],"https://app.prntscr.com/en/download.html","","u"),
E("PicPick",["picpick"],"https://picpick.app/en/download","","u"),
E("FastStone Capture",["faststone capture"],"https://www.faststone.org/FSCaptureDownload.htm","","u"),
E("Flameshot",["flameshot"],"https://flameshot.org/","","u"),
E("GPU-Z",["gpuz","gpu-z"],"https://www.techpowerup.com/gpuz/","","u"),
E("HWMonitor",["hwmonitor"],"https://www.cpuid.com/softwares/hwmonitor.html","","u"),
E("HWiNFO",["hwinfo"],"https://www.hwinfo.com/download/","","u"),
E("Speccy",["speccy"],"https://www.ccleaner.com/speccy/download/","","u"),
E("CrystalDiskInfo",["crystaldiskinfo"],"https://crystalmark.info/en/download/","","u"),
E("CrystalDiskMark",["crystaldiskmark"],"https://crystalmark.info/en/download/","","u"),
E("AIDA64",["aida64"],"https://www.aida64.com/downloads","","u"),
E("FurMark",["furmark"],"https://geeks3d.com/furmark/","","u"),
E("MSI Afterburner",["msi afterburner","afterburner"],"https://www.msi.com/Landing/afterburner/graphics-cards","","u"),
E("CCleaner",["ccleaner"],"https://www.ccleaner.com/ccleaner/download/","","u"),
E("Glary Utilities",["glary utilities"],"https://www.glarysoft.com/glary-utilities/","","u"),
E("Wise Care 365",["wise care 365"],"https://www.wisecleaner.com/wise-care-365.html","","u"),
E("Defraggler",["defraggler"],"https://www.ccleaner.com/defraggler/download/","","u"),
E("Recuva",["recuva"],"https://www.ccleaner.com/recuva/download/","","u"),
E("EaseUS Data Recovery",["easeus"],"https://www.easeus.com/datarecoverywizard/","","u"),
E("AOMEI Backupper",["aomei"],"https://www.aomeitech.com/aomei-backupper.html","","u"),
E("Rufus",["rufus"],"https://rufus.ie/en/","","u"),
E("BalenaEtcher",["balenaetcher","etcher"],"https://www.balena.io/etcher/","","u"),
E("Ventoy",["ventoy"],"https://www.ventoy.net/en/download.html","","u"),
E("WinToUSB",["wintousb"],"https://www.easyuefi.com/wintousb/","","u"),
E("HxD Hex Editor",["hxd","hex editor"],"https://mh-nexus.de/en/hxd/","","u"),
E("Beyond Compare",["beyond compare"],"https://www.scootersoftware.com/download","","u"),
E("WinMerge",["winmerge"],"https://winmerge.org/downloads/","","u"),
E("Meld",["meld"],"https://meldmerge.org/","","u"),
E("TreeSize Free",["treesize"],"https://www.jam-software.com/treesize_free","","u"),
E("WizTree",["wiztree"],"https://diskanalyzer.com/","","u"),
E("SpaceSniffer",["spacesniffer"],"http://www.uderzo.it/main_products/space_sniffer/","","u"),
E("WinDirStat",["windirstat"],"https://windirstat.net/","","u"),
E("LockHunter",["lockhunter"],"https://lockhunter.com/","","u"),
E("Process Explorer",["process explorer","procexp"],"https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer","","u"),
E("Autoruns",["autoruns"],"https://learn.microsoft.com/en-us/sysinternals/downloads/autoruns","","u"),
E("Sysinternals Suite",["sysinternals"],"https://learn.microsoft.com/en-us/sysinternals/downloads/sysinternals-suite","","u"),
E("ConEmu",["conemu"],"https://conemu.github.io/","","u"),
E("Cmder",["cmder"],"https://cmder.app/","","u"),
E("Alacritty",["alacritty"],"https://alacritty.org/","","u"),
E("Flow Launcher",["flow launcher"],"https://www.flowlauncher.com/","","u"),
E("Listary",["listary"],"https://www.listary.com/","","u"),
E("Wox",["wox"],"https://github.com/Wox-launcher/Wox","","u"),
E("Keypirinha",["keypirinha"],"https://keypirinha.com/","","u"),
E("Dism++",["dism++","dismpp"],"https://github.com/Chuyu-Team/Dism-Multi-language","","u"),
E("Geek Uninstaller",["geek uninstaller"],"https://geekuninstaller.com/","","u"),
E("Revo Uninstaller",["revo uninstaller"],"https://www.revouninstaller.com/","","u"),
E("IObit Uninstaller",["iobit uninstaller"],"https://www.iobit.com/en/advanceduninstaller.php","","u"),
E("Notepad3",["notepad3"],"https://github.com/rizonesoft/Notepad3","","u"),
E("TeraCopy",["teracopy"],"https://www.codesector.com/teracopy","","u"),
E("qBittorrent",["qbittorrent"],"https://www.qbittorrent.org/","","u"),
E("Internet Download Manager",["idm","internet download manager"],"https://www.internetdownloadmanager.com/","","u"),
E("Duplicate Cleaner",["duplicate cleaner"],"https://www.digitalvolcano.co.uk/duplicatecleaner.html","","u"),
E("Macrium Reflect",["macrium reflect"],"https://www.macrium.com/reflectfree","","u"),
E("Microsoft Office 2021",["office 2021","microsoft office 2021"],"https://www.microsoft.com/en-us/microsoft-365","","p"),
E("Office 365",["office 365","microsoft 365"],"https://www.microsoft.com/en-us/microsoft-365","","p"),
E("OpenOffice",["openoffice","apache openoffice"],"https://www.openoffice.org/download/","","p"),
E("Foxit Reader",["foxit","foxit reader"],"https://www.foxit.com/pdf-reader/","","p"),
E("Adobe Acrobat Reader",["acrobat reader","adobe reader"],"https://get.adobe.com/reader/","","p"),
E("Sumatra PDF",["sumatra pdf","sumatra"],"https://www.sumatrapdfreader.org/download-free-pdf-viewer","","p"),
E("Nitro PDF Reader",["nitro pdf","nitro"],"https://www.gonitro.com/pdf-reader/download","","p"),
E("PDF24 Creator",["pdf24","pdf24 creator"],"https://tools.pdf24.org/en/creator","","p"),
E("Obsidian",["obsidian"],"https://obsidian.md/download","","p"),
E("OneNote",["onenote"],"https://www.onenote.com/download","","p"),
E("Evernote",["evernote"],"https://evernote.com/download","","p"),
E("Joplin",["joplin"],"https://joplinapp.org/","","p"),
E("Standard Notes",["standard notes"],"https://standardnotes.com/","","p"),
E("Todoist",["todoist"],"https://todoist.com/downloads","","p"),
E("Microsoft To Do",["microsoft to do","ms todo"],"https://todo.microsoft.com/tasks/","","p"),
E("TickTick",["ticktick"],"https://ticktick.com/download","","p"),
E("Monday.com",["monday.com","monday"],"https://monday.com/","","p"),
E("XMind",["xmind"],"https://xmind.app/download/","","p"),
E("Zotero",["zotero"],"https://www.zotero.org/download/","","p"),
E("Calibre",["calibre"],"https://calibre-ebook.com/download","","p"),
E("Draw.io",["draw.io","diagrams.net"],"https://www.diagrams.net/","","p"),
E("ClickUp",["clickup"],"https://clickup.com/download","","p"),
E("Zoho Notebook",["zoho notebook"],"https://www.zoho.com/notebook/download/","","p"),
E("Steam",["steam"],"https://store.steampowered.com/","https://cdn.cloudflare.steamstatic.com/client/installer/SteamSetup.exe","G"),
E("Epic Games Launcher",["epic games","epic"],"https://store.epicgames.com/","","G"),
E("EA App",["ea app","origin","ea"],"https://www.ea.com/ea-app","","G"),
E("Ubisoft Connect",["ubisoft connect","uplay"],"https://ubisoftconnect.com/","","G"),
E("GOG Galaxy",["gog galaxy","gog"],"https://www.gog.com/galaxy","","G"),
E("Battle.net",["battle.net","blizzard"],"https://www.blizzard.com/download/","","G"),
E("Xbox App",["xbox","xbox app"],"https://www.xbox.com/en-US/apps/xbox-app-for-pc","","G"),
E("Itch.io",["itch.io","itch"],"https://itch.io/app","","G"),
E("Minecraft Launcher",["minecraft"],"https://www.minecraft.net/en-us/download","","G"),
E("Riot Client",["riot client","league of legends","valorant"],"https://riotgames.com/","","G"),
E("WeGame",["wegame"],"https://www.wegame.com.cn/","","G"),
E("NetEase Games",["netease games","netease"],"https://game.163.com/","","G"),
E("PlayStation Plus",["playstation plus","ps plus"],"https://www.playstation.com/ps-plus/","","G"),
E("Rockstar Games Launcher",["rockstar","rockstar games"],"https://socialclub.rockstargames.com/","","G"),
E("Parsec",["parsec"],"https://parsec.app/downloads","","G"),
E("Google Drive",["google drive","gdrive"],"https://www.google.com/drive/download/","","o"),
E("Dropbox",["dropbox"],"https://www.dropbox.com/install","","o"),
E("OneDrive",["onedrive","microsoft onedrive"],"https://www.microsoft.com/en-us/microsoft-365/onedrive","","o"),
E("TeamViewer",["teamviewer"],"https://www.teamviewer.com/en/download/","","o"),
E("AnyDesk",["anydesk"],"https://anydesk.com/en/downloads/windows","","o"),
E("RustDesk",["rustdesk"],"https://rustdesk.com/","","o"),
E("VMware Horizon Client",["vmware horizon","horizon client"],"https://customerconnect.vmware.com/en/downloads/","","o"),
E("Cisco AnyConnect",["anyconnect","cisco anyconnect"],"https://www.cisco.com/c/en/us/products/security/anyconnect-secure-mobility-client/","","o"),
E("FortiClient",["forticlient","fortinet"],"https://www.fortinet.com/support/product-downloads","","o"),
E("Google Earth",["google earth"],"https://www.google.com/earth/about/versions/","","o"),
E("Microsoft Power BI",["power bi","microsoft power bi"],"https://powerbi.microsoft.com/en-us/downloads/","","o"),
E("Tableau Desktop",["tableau","tableau desktop"],"https://www.tableau.com/products/desktop/download","","o"),
E("MATLAB",["matlab"],"https://www.mathworks.com/downloads/","","o"),
E("OriginPro",["origin","originlab"],"https://www.originlab.com/","","o"),
E("SketchUp",["sketchup"],"https://www.sketchup.com/","","o"),
E("Baidu Netdisk",["baidu netdisk","baidupan"],"https://pan.baidu.com/download/","","o"),
E("Aliyun Drive",["aliyundrive","aliyun drive"],"https://www.aliyundrive.com/download","","o"),
E("XnView",["xnview"],"https://www.xnview.com/en/xnviewmp/","","o"),
E("IrfanView",["irfanview"],"https://www.irfanview.com/","","o"),
E("Honeyview",["honeyview"],"https://www.bandisoft.com/honeyview/","","o"),
E("Thunder",["thunder","xunlei"],"https://www.xunlei.com/","","o"),
E("Sunlogin",["sunlogin","sunflower"],"https://sunlogin.oray.com/download/","","o"),
E("Baidu IME",["baidu ime","baidu input method"],"https://shurufa.baidu.com/","","o"),
E("Sogou IME",["sogou ime","sogou input method"],"https://pinyin.sogou.com/","","o"),
E("AutoDesk Revit",["revit","autodesk revit"],"https://www.autodesk.com/products/revit/","","o"),
E("WinPcap",["winpcap"],"https://www.winpcap.org/","","o"),
E("Npcap",["npcap"],"https://npcap.com/","","o"),
]);
// === NEW: Games, streaming, AI, video editing (user requested) ===
ad([
E("Steam China",["steam china","蒸汽平台"],"https://store.steamchina.com/","","G"),
E("Pinduoduo",["pinduoduo","拼多多"],"https://www.pinduoduo.com/","","G"),
E("Honor of Kings",["honor of kings","王者荣耀"],"https://pvp.qq.com/","","G"),
E("Genshin Impact",["genshin impact","原神"],"https://genshin.hoyoverse.com/","","G"),
E("NVIDIA GeForce Now",["geforce now","nvidia geforce now"],"https://www.nvidia.com/en-us/geforce-now/","","G"),
E("Steam Deck",["steam deck"],"https://www.steamdeck.com/","","G"),

// === Video/Drama Streaming Desktop Apps ===
E("Bilibili",["bilibili","b站"],"https://www.bilibili.com/","","m"),
E("iQiyi",["iqiyi","爱奇艺"],"https://www.iqiyi.com/","","m"),
E("Tencent Video",["tencent video","腾讯视频"],"https://v.qq.com/","","m"),
E("Youku",["youku","优酷"],"https://www.youku.com/","","m"),
E("Mango TV",["mango tv","芒果tv"],"https://www.mgtv.com/","","m"),
E("Douyin",["douyin","抖音"],"https://www.douyin.com/","","m"),
E("Kuaishou",["kuaishou","快手"],"https://www.kuaishou.com/","","m"),
E("Twitch Studio",["twitch","twitch studio"],"https://www.twitch.tv/downloads","","m"),
E("Netflix",["netflix"],"https://www.netflix.com/","","m"),
E("YouTube Music",["youtube music","yt music"],"https://music.youtube.com/","","m"),
E("HBO Max",["hbo max","hbomax"],"https://www.hbomax.com/","","m"),
E("Disney+",["disney+"],"https://www.disneyplus.com/","","m"),
E("Crunchyroll",["crunchyroll"],"https://www.crunchyroll.com/","","m"),

// === Music Production & Players ===
E("NetEase Music",["netease music","网易云音乐"],"https://music.163.com/","","m"),
E("QQ Music",["qq music","qq音乐"],"https://y.qq.com/","","m"),
E("CoolDog",["kugou","酷狗音乐"],"https://www.kugou.com/","","m"),
E("Kuwo",["kuwo","酷我音乐"],"https://www.kuwo.cn/","","m"),
E("Xiami Music",["xiami","虾米音乐"],"https://www.xiami.com/","","m"),
E("Plex",["plex","plex media server"],"https://www.plex.tv/","","m"),
E("Jellyfin",["jellyfin"],"https://jellyfin.org/","","m"),
E("Emby",["emby"],"https://emby.media/","","m"),
E("Kodi",["kodi"],"https://kodi.tv/download","","m"),
E("Foobar2000",["foobar2000","foobar"],"https://www.foobar2000.org/download","","m"),
E("MusicBee",["musicbee"],"https://getmusicbee.com/","","m"),
E("Mixxx",["mixxx"],"https://mixxx.org/download/","","m"),
E("Serato DJ",["serato","serato dj"],"https://serato.com/dj","","m"),
E("Traktor",["traktor"],"https://www.native-instruments.com/en/products/traktor/","","m"),

// === Video Editing (additional) ===
E("剪映专业版",["剪映","capcut","jianying"],"https://www.capcut.com/","","m"),
E("必剪",["必剪","bcut"],"https://bcut.baidu.com/","","m"),
E("Vegas Pro",["vegas","vegas pro","sony vegas"],"https://www.vegascreativesoftware.com/","","m"),
E("Camtasia",["camtasia","techsmith camtasia"],"https://www.techsmith.com/camtasia.html","","m"),
E("Filmora",["filmora","wondershare filmora"],"https://filmora.wondershare.com/","","m"),
E("Lightworks",["lightworks"],"https://lwks.com/","","m"),
E("HitFilm",["hitfilm","hitfilm express"],"https://fxhome.com/hitfilm","","m"),
E("Motion",["motion","apple motion"],"https://www.apple.com/final-cut-pro/motion/","","m"),
E("Blender Video Editor",["blender video"],"https://www.blender.org/","","m"),
E("Olive Video Editor",["olive"],"https://olivevideoeditor.org/","","m"),

// === AI Tools ===
E("ChatGPT Desktop",["chatgpt","openai chatgpt"],"https://chatgpt.com/","","o"),
E("Ollama",["ollama"],"https://ollama.com/","","o"),
E("LM Studio",["lm studio","lmstudio"],"https://lmstudio.ai/","","o"),
E("Stable Diffusion WebUI",["stable diffusion","sd webui"],"https://github.com/AUTOMATIC1111/stable-diffusion-webui","","o"),
E("ComfyUI",["comfyui","comfy ui"],"https://github.com/comfyanonymous/ComfyUI","","o"),
E("Fooocus",["fooocus"],"https://github.com/lllyasviel/Fooocus","","o"),
E("Amber",["amber","amber ai"],"https://amber.ai/","","o"),
E("Hugging Face Desktop",["hugging face","huggingface"],"https://huggingface.co/","","o"),
E("Lobe Chat",["lobe chat","lobe"],"https://lobehub.com/","","o"),
E("Jan",["jan","jan ai"],"https://jan.ai/","","o"),
E("GPT4All",["gpt4all"],"https://gpt4all.io/","","o"),
E("Text Generation WebUI",["text generation webui","oobabooga"],"https://github.com/oobabooga/text-generation-webui","","o"),
E("KoboldCPP",["koboldcpp"],"https://github.com/LostRuins/koboldcpp","","o"),
E("Msty",["msty"],"https://msty.app/","","o"),
E("Cursor",["cursor","cursor ai"],"https://www.cursor.com/","","d"),
E("GitHub Copilot",["github copilot","copilot"],"https://github.com/features/copilot","","d"),
E("Cline",["cline","claude code"],"https://github.com/cline/cline","","d"),
E("Continue",["continue.dev","continue"],"https://continue.dev/","","d"),
E("Codeium",["codeium","windsurf"],"https://codeium.com/","","d"),

// === More Security Tools ===
E("Spybot Search & Destroy",["spybot"],"https://www.safer-networking.org/","","s"),
E("SuperAntiSpyware",["superantispyware"],"https://www.superantispyware.com/","","s"),
E("Malwarebytes Anti-Malware",["malwarebytes anti-malware"],"https://www.malwarebytes.com/","","s"),
E("TinyWall",["tinywall"],"https://tinywall.pados.hu/","","s"),
E("Simplewall",["simplewall"],"https://github.com/henrypp/simplewall","","s"),
E("NetLimiter",["netlimiter"],"https://www.netlimiter.com/","","s"),
E("Sandboxie",["sandboxie"],"https://sandboxie-plus.com/","","s"),
E("Windows Firewall Control",["windows firewall control","wfc"],"https://www.binisoft.org/wfc","","s"),
E("Autorun Organizer",["autorun organizer"],"https://www.chemtable.com/autorun-organizer.htm","","s"),
E("O&O ShutUp10",["o&o shutup10","shutup10"],"https://www.oo-software.com/en/shutup10","","s"),
E("WPD",["wpd","windows privacy dashboard"],"https://wpd.app/","","s"),
E("Privacy Eraser",["privacy eraser"],"https://privacyeraser.com/","","s"),
E("BleachBit",["bleachbit"],"https://www.bleachbit.org/","","s"),
E("TCPView",["tcpview"],"https://learn.microsoft.com/en-us/sysinternals/downloads/tcpview","","s"),
E("Nmap",["nmap"],"https://nmap.org/download.html","","s"),
E("Zenmap",["zenmap"],"https://nmap.org/zenmap/","","s"),
E("Metasploit",["metasploit","msf"],"https://www.metasploit.com/","","s"),
E("Burp Suite",["burp suite","burp"],"https://portswigger.net/burp","","s"),
E("Acunetix",["acunetix"],"https://www.acunetix.com/","","s"),
E("Nessus",["nessus"],"https://www.tenable.com/downloads/nessus","","s"),

// === More Games (Popular Titles) ===
E("League of Legends",["league of legends","lol"],"https://www.leagueoflegends.com/","","G"),
E("Valorant",["valorant"],"https://playvalorant.com/","","G"),
E("Counter-Strike 2",["counter-strike","cs2","csgo"],"https://www.counter-strike.net/","","G"),
E("Dota 2",["dota 2","dota2"],"https://www.dota2.com/","","G"),
E("PUBG",["pubg","pubg battlegrounds"],"https://pubg.com/","","G"),
E("Apex Legends",["apex legends","apex"],"https://www.ea.com/games/apex-legends","","G"),
E("Call of Duty",["call of duty","cod","warzone"],"https://www.callofduty.com/","","G"),
E("Fortnite",["fortnite"],"https://www.fortnite.com/","","G"),
E("GTA V",["gta v","grand theft auto"],"https://www.rockstargames.com/GTAV","","G"),
E("Overwatch 2",["overwatch","ow2"],"https://overwatch.blizzard.com/","","G"),
E("World of Warcraft",["world of warcraft","wow"],"https://worldofwarcraft.blizzard.com/","","G"),
E("Diablo IV",["diablo","diablo iv"],"https://diablo4.blizzard.com/","","G"),
E("Hearthstone",["hearthstone"],"https://hearthstone.blizzard.com/","","G"),
E("StarCraft II",["starcraft","starcraft ii"],"https://starcraft2.blizzard.com/","","G"),
E("Destiny 2",["destiny 2","destiny2"],"https://www.bungie.net/destiny2","","G"),
E("Warframe",["warframe"],"https://www.warframe.com/","","G"),
E("Path of Exile",["path of exile","poe"],"https://www.pathofexile.com/","","G"),
E("Final Fantasy XIV",["final fantasy xiv","ffxiv","ff14"],"https://www.finalfantasyxiv.com/","","G"),
E("Genshin Impact",["genshin impact","原神"],"https://genshin.hoyoverse.com/","","G"),
E("Honkai Star Rail",["honkai star rail","星穹铁道"],"https://hsr.hoyoverse.com/","","G"),
E("Zenless Zone Zero",["zzz","zenless zone zero"],"https://zenless.hoyoverse.com/","","G"),
E("Minecraft Java Edition",["minecraft java"],"https://www.minecraft.net/","","G"),
E("Terraria",["terraria"],"https://terraria.org/","","G"),
E("Cyberpunk 2077",["cyberpunk 2077","cyberpunk"],"https://www.cyberpunk.net/","","G"),
E("Elden Ring",["elden ring"],"https://www.eldenring.com/","","G"),
E("Red Dead Redemption 2",["red dead redemption 2","rdr2","red dead"],"https://www.rockstargames.com/reddeadredemption2","","G"),
E("Hogwarts Legacy",["hogwarts legacy"],"https://www.hogwartslegacy.com/","","G"),
E("Baldur's Gate 3",["baldur's gate 3","bg3","baldurs gate"],"https://baldursgate3.game/","","G"),
E("Black Myth Wukong",["black myth wukong","黑神话悟空"],"https://www.heishenhua.com/","","G"),

// === More Wine/Utilities ===
E("Windows 11 Manager",["windows 11 manager"],"https://www.yrnm.com/","","u"),
E("StartAllBack",["startallback"],"https://www.startallback.com/","","u"),
E("Start11",["start11"],"https://www.stardock.com/products/start11/","","u"),
E("ExplorerPatcher",["explorerpatcher"],"https://github.com/valinet/ExplorerPatcher","","u"),
E("OldNewExplorer",["oldnewexplorer"],"https://www.msfn.org/board/topic/170375-oldnewexplorer-118/","","u"),
E("MacType",["mactype"],"https://www.mactype.net/","","u"),
E("TrafficMonitor",["trafficmonitor"],"https://github.com/zhongyang219/TrafficMonitor","","u"),
E("NetSpeedMonitor",["netspeedmonitor"],"https://www.netspeedmonitor.net/","","u"),
E("TranslucentTB",["translucenttb"],"https://github.com/TranslucentTB/TranslucentTB","","u"),
E("EarTrumpet",["eartrumpet"],"https://github.com/File-New-Project/EarTrumpet","","u"),
E("ModernFlyouts",["modernflyouts"],"https://github.com/ModernFlyouts-Community/ModernFlyouts","","u"),
E("TrayS",["trays"],"https://github.com/zhongyang219/TrafficMonitor","","u"),
E("Fences",["fences","stardock fences"],"https://www.stardock.com/products/fences/","","u"),
E("Groupy",["groupy"],"https://www.stardock.com/products/groupy/","","u"),
E("DisplayFusion",["displayfusion"],"https://www.displayfusion.com/","","u"),
E("Dual Monitor Tools",["dual monitor tools"],"https://dualmonitortools.sourceforge.net/","","u"),
E("Mouse Without Borders",["mouse without borders"],"https://www.microsoft.com/en-us/garage/profiles/mouse-without-borders/","","u"),
E("Synergy",["synergy"],"https://symless.com/synergy","","u"),
E("Barrier",["barrier"],"https://github.com/debauchee/barrier","","u"),
E("KDE Connect",["kde connect"],"https://kdeconnect.kde.org/","","u"),
E("Intel Unison",["intel unison","unison"],"https://www.intel.com/content/www/us/en/products/docs/unison/overview.html","","u"),
E("Link to Windows",["link to windows","phone link"],"https://www.microsoft.com/en-us/windows/sync-across-your-devices","","u"),
E("RoundedTB",["roundedtb"],"https://github.com/torchgm/RoundedTB","","u"),
E("Droplt",["droplt","dropit"],"https://www.dropitproject.com/","","u"),
E("CopyQ",["copyq"],"https://hluk.github.io/CopyQ/","","u"),
E("Ditto Clipboard",["ditto","ditto clipboard"],"https://ditto-cp.sourceforge.io/","","u"),
E("ClipX",["clipx"],"https://bluemars.org/clipx/","","u"),
E("TouchCursor",["touchcursor"],"https://touchcursor.sourceforge.net/","","u"),
E("Hunt and Peck",["hunt and peck"],"https://huntandpeck.sourceforge.net/","","u"),
E("Min",["min","min browser"],"https://minbrowser.org/","","b"),

// === More Security (CN-focused) ===
E("AnTian Antivirus",["antian antivirus","安天杀毒"],"https://www.antiy.cn/","","s"),
E("Venustech",["venustech","启明星辰"],"https://www.venustech.com.cn/","","s"),
E("深信服",["深信服","sangfor"],"https://www.sangfor.com/","","s"),
E("天融信",["天融信","topsec"],"https://www.topsec.com.cn/","","s"),
E("绿盟科技",["绿盟科技","nsfocus"],"https://www.nsfocus.com/","","s"),
E("奇安信",["奇安信","qianxin"],"https://www.qianxin.com/","","s"),
E("360 Safety Guard",["360 safety guard","360安全卫士"],"https://www.360.cn/","","s"),
E("360 Antivirus",["360 antivirus","360杀毒"],"https://www.360.cn/","","s"),
E("Tencent PC Manager",["tencent pc manager","腾讯电脑管家"],"https://guanjia.qq.com/","","s"),
E("Alibaba SafeGuard",["alibaba safeguard","阿里安全"],"https://safe.alibaba.com/","","s"),

// === More Tools ===
E("Diagrams.net Desktop",["diagrams.net desktop","draw.io desktop"],"https://www.diagrams.net/","","u"),
E("PlantUML",["plantuml"],"https://plantuml.com/","","u"),
E("Mermaid",["mermaid","mermaid editor"],"https://mermaid.js.org/","","u"),
E("DB Browser for SQLite",["db browser for sqlite","sqlitebrowser"],"https://sqlitebrowser.org/","","D"),
E("Redis Commander",["redis commander"],"https://joeferner.github.io/redis-commander/","","D"),
E("MongoDB Shell",["mongosh","mongodb shell"],"https://www.mongodb.com/try/download/shell","","D"),
E("pgAdmin",["pgadmin"],"https://www.pgadmin.org/download/","","D"),
E("Azure Cosmos DB",["azure cosmos db","cosmos db"],"https://learn.microsoft.com/en-us/azure/cosmos-db/","","D"),

// === More AI ===
E("TensorFlow",["tensorflow","tf"],"https://www.tensorflow.org/","","r"),
E("PyTorch",["pytorch","torch"],"https://pytorch.org/","","r"),
E("CUDA Toolkit",["cuda toolkit","nvidia cuda"],"https://developer.nvidia.com/cuda-downloads","","r"),
E("cuDNN",["cudnn"],"https://developer.nvidia.com/cudnn","","r"),
E("ONNX Runtime",["onnx","onnx runtime"],"https://onnxruntime.ai/","","r"),
E("OpenCV",["opencv"],"https://opencv.org/","","r"),
E("PaddlePaddle",["paddlepaddle","paddle"],"https://www.paddlepaddle.org.cn/","","r"),
E("MindSpore",["mindspore","huawei mindspore"],"https://www.mindspore.cn/","","r"),
E("MLflow",["mlflow"],"https://mlflow.org/","","r"),
E("Weights & Biases",["weights and biases","wandb"],"https://wandb.ai/","","r"),
E("LabelImg",["labelimg"],"https://github.com/heartexlabs/labelImg","","r"),
E("Label Studio",["label studio"],"https://labelstud.io/","","r"),
E("Roboflow",["roboflow"],"https://roboflow.com/","","r"),
E("Ultralytics",["ultralytics","yolo"],"https://www.ultralytics.com/","","r"),
E("EasyOCR",["easyocr"],"https://github.com/JaidedAI/EasyOCR","","r"),
E("Tesseract OCR",["tesseract","tesseract ocr"],"https://github.com/tesseract-ocr/tesseract","","r"),
]);
// === More: Chinese-specific, additional tools ===
ad([
E("WPS Presentation",["wps演示","wpp"],"https://www.wps.com/","","p"),
E("WPS Spreadsheets",["wps表格","wps excel","et"],"https://www.wps.com/","","p"),
E("Eagle",["eagle","eagle app"],"https://eagle.cool/","","g"),
E("Billfish",["billfish"],"https://www.billfish.cn/","","g"),
E("Pixpin",["pixpin"],"https://pixpinapp.com/","","u"),
E("uTools",["utools"],"https://u.tools/","","u"),
E("Hibit Uninstaller",["hibit uninstaller"],"https://hibitsoft.ir/Uninstaller.html","","u"),
E("Bulk Crap Uninstaller",["bulk crap uninstaller","bcu"],"https://www.bcuninstaller.com/","","u"),
E("WizTree",["wiztree"],"https://diskanalyzer.com/","","u"),
E("Folder Size",["folder size"],"https://foldersize.sourceforge.net/","","u"),
E("MouseClick",["mouseclick","鼠标连点器"],"https://www.mouseclick.cn/","","u"),
E("OP Auto Clicker",["op auto clicker","autoclicker"],"https://opautoclicker.com/","","u"),
E("RPA Helper",["rpa helper","rpa"],"https://rpa.qq.com/","","u"),
E("QuickLook",["quicklook"],"https://github.com/QL-Win/QuickLook","","u"),
E("Seer",["seer"],"https://www.1234.sh/","","u"),
E("DesktopOK",["desktopok"],"https://www.softwareok.com/?seite=DesktopOK","","u"),
E("RocketDock",["rocketdock"],"https://rocketdock.com/","","u"),
E("Nimi Places",["nimi places"],"https://www.nimiplaces.com/","","u"),
E("WinStep Nexus",["winstep nexus","nexus dock"],"https://www.winstep.net/nexus.asp","","u"),
E("TaskbarX",["taskbarx"],"https://github.com/ChrisAnd1998/TaskbarX","","u"),
E("T-Clock",["t-clock"],"https://github.com/White-Tiger/T-Clock","","u"),
E("8GadgetPack",["8gadgetpack"],"https://8gadgetpack.net/","","u"),
E("Rainmeter",["rainmeter"],"https://www.rainmeter.net/","","u"),
E("Wallpaper Engine",["wallpaper engine"],"https://www.wallpaperengine.io/","","u"),
E("Live Wallpaper",["live wallpaper","灵动壁纸"],"https://www.wallpaperengine.io/","","u"),
E("ScreenToGif",["screentogif"],"https://www.screentogif.com/","","u"),
E("GifCam",["gifcam"],"https://blog.bahraniapps.com/gifcam/","","u"),
E("LICEcap",["licecap"],"https://www.cockos.com/licecap/","","u"),
E("OBS Studio",["obs studio","obs"],"https://obsproject.com/","","m"),
E("StreamElements",["streamelements"],"https://streamelements.com/","","m"),
E("NVIDIA Broadcast",["nvidia broadcast"],"https://www.nvidia.com/en-us/broadcast/","","m"),
E("NVIDIA GeForce Experience",["geforce experience"],"https://www.nvidia.com/en-us/geforce/geforce-experience/","","m"),
E("AMD Adrenalin",["amd adrenalin","amd software"],"https://www.amd.com/en/technologies/software","","m"),
E("Intel Graphics Command Center",["intel graphics"],"https://www.intel.com/content/www/us/en/download/","","m"),
E("DS4Windows",["ds4windows"],"https://ds4-windows.com/","","G"),
E("InputMapper",["inputmapper"],"https://inputmapper.com/","","G"),
E("JoyToKey",["joytokey"],"https://joytokey.net/","","G"),
E("X360CE",["x360ce"],"https://www.x360ce.com/","","G"),
E("ReWASD",["rewasd"],"https://www.rewasd.com/","","G"),
E("Playnite",["playnite"],"https://playnite.link/","","G"),
E("Launchbox",["launchbox"],"https://www.launchbox-app.com/","","G"),
E("RetroArch",["retroarch"],"https://www.retroarch.com/","","G"),
E("Dolphin Emulator",["dolphin emulator","dolphin"],"https://dolphin-emu.org/","","G"),
E("PCSX2",["pcsx2"],"https://pcsx2.net/","","G"),
E("RPCS3",["rpcs3"],"https://rpcs3.net/","","G"),
E("Citra",["citra"],"https://citra-emulator.org/","","G"),
E("Cemu",["cemu"],"https://cemu.info/","","G"),
E("Yuzu",["yuzu"],"https://yuzu-emu.org/","","G"),
E("Ryujinx",["ryujinx"],"https://ryujinx.org/","","G"),
E("MAME",["mame"],"https://www.mamedev.org/","","G"),
E("PPSSPP",["ppsspp"],"https://www.ppsspp.org/","","G"),
E("Red Dead Redemption 2",["red dead redemption 2","rdr2"],"https://www.rockstargames.com/reddeadredemption2","","G"),
E("The Witcher 3",["the witcher 3","witcher 3"],"https://www.thewitcher.com/","","G"),
E("Sekiro",["sekiro","只狼"],"https://www.sekiro.com/","","G"),
E("Monster Hunter World",["monster hunter world","mhw"],"https://www.monsterhunter.com/","","G"),
E("Monster Hunter Rise",["monster hunter rise","mhr"],"https://www.monsterhunter.com/","","G"),
E("Persona 5",["persona 5","p5r"],"https://www.atlus.com/persona5/","","G"),
E("Nier Automata",["nier automata"],"https://nierautomata.com/","","G"),
E("Ghost of Tsushima",["ghost of tsushima"],"https://www.suckerpunch.com/","","G"),
E("God of War",["god of war"],"https://godofwar.playstation.com/","","G"),
E("Spider-Man",["spider-man","spiderman"],"https://insomniac.games/game/spider-man-remastered/","","G"),
E("Horizon Zero Dawn",["horizon zero dawn"],"https://www.guerilla-games.com/","","G"),
E("Stray",["stray"],"https://stray.game/","","G"),
E("Hades",["hades"],"https://www.supergiantgames.com/games/hades/","","G"),
E("Disco Elysium",["disco elysium"],"https://discoelysium.com/","","G"),
E("Microsoft Flight Simulator",["microsoft flight simulator","flight sim"],"https://www.flightsimulator.com/","","G"),
E("Forza Horizon 5",["forza horizon 5","forza"],"https://forza.net/","","G"),
E("Halo Infinite",["halo infinite","halo"],"https://www.halowaypoint.com/","","G"),
E("Age of Empires IV",["age of empires iv","aoe4"],"https://www.ageofempires.com/","","G"),
E("Starfield",["starfield"],"https://starfieldgame.com/","","G"),
E("Stardew Valley",["stardew valley"],"https://www.stardewvalley.net/","","G"),
E("RimWorld",["rimworld"],"https://rimworldgame.com/","","G"),
E("Factorio",["factorio"],"https://factorio.com/","","G"),
E("Satisfactory",["satisfactory"],"https://www.satisfactorygame.com/","","G"),
E("Subnautica",["subnautica"],"https://unknownworlds.com/subnautica/","","G"),
E("Cuphead",["cuphead"],"https://cupheadgame.com/","","G"),
E("Hollow Knight",["hollow knight"],"https://hollowknight.com/","","G"),
E("Celeste",["celeste"],"https://celestegame.com/","","G"),
E("Dead Cells",["dead cells"],"https://dead-cells.com/","","G"),
E("Hades II",["hades ii","hades 2"],"https://www.supergiantgames.com/games/hades-ii/","","G"),
E("Dark Souls III",["dark souls iii","dark souls 3"],"https://www.bandainamcoent.com/games/dark-souls-3","","G"),
E("Elden Ring",["elden ring"],"https://www.eldenring.com/","","G"),
E("Sekiro Shadows Die Twice",["sekiro shadows die twice"],"https://www.sekiro.com/","","G"),
E("Resident Evil 4",["resident evil 4","re4"],"https://www.residentevil.com/","","G"),
E("Resident Evil Village",["resident evil village","re8"],"https://www.residentevil.com/village/","","G"),
E("Silent Hill 2",["silent hill 2","sh2"],"https://www.konami.com/games/","","G"),
]);
// Fix office -> productivity
for (const e of entries) {
  if (e.category === "office") e.category = "productivity";
}

// Deduplicate by name (keep first occurrence)
const seen2 = new Set();
const deduped = [];
for (const e of entries) {
  if (!seen2.has(e.software_name)) {
    seen2.add(e.software_name);
    deduped.push(e);
  }
}

deduped.sort((a, b) => a.category.localeCompare(b.category) || a.software_name.localeCompare(b.software_name));
fs.writeFileSync(f, JSON.stringify(deduped, null, 2), "utf-8");
console.log("Total entries:", deduped.length);
const cats = {};
deduped.forEach(e => { cats[e.category] = (cats[e.category] || 0) + 1; });
console.log("By category:", JSON.stringify(cats));
