const fs = require("fs");
const path = require("path");
const f = path.join(__dirname,"..","data","builtin-links.json");
const M={b:"browser",d:"development",r:"runtime",D:"database",g:"design",c:"communication",m:"media",s:"security",u:"utility",p:"productivity",G:"game",o:"other"};
function E(n,a,o,dl,c){return{software_name:n,aliases:a.map(x=>x.toLowerCase()),official_url:o,direct_download_url:dl||"",category:M[c]||c,verified:true}}
const entries=JSON.parse(fs.readFileSync(f,"utf-8"));
const seen=new Set(entries.map(e=>e.software_name));
let a=0;
function ad(arr){for(const e of arr){if(!seen.has(e.software_name)){seen.add(e.software_name);entries.push(e);a++;}}}
ad([
E("Opera",["opera","opera browser"],"https://www.opera.com/download","https://net.geo.opera.com/opera/stable/windows","b"),
E("Vivaldi",["vivaldi","vivaldi browser"],"https://vivaldi.com/download/","","b"),
E("Tor Browser",["tor","tor browser","torbrowser"],"https://www.torproject.org/download/","","b"),
E("Yandex Browser",["yandex","yandex browser"],"https://browser.yandex.com/","","b"),
E("Arc Browser",["arc","arc browser"],"https://arc.net/","","b"),
E("Maxthon",["maxthon","maxthon browser"],"https://www.maxthon.com/","","b"),
E("Pale Moon",["palemoon","pale moon"],"https://www.palemoon.org/","","b"),
E("Waterfox",["waterfox"],"https://www.waterfox.net/","","b"),
E("Cent Browser",["cent","cent browser"],"https://www.centbrowser.com/","","b"),
E("Kiwi Browser",["kiwi","kiwi browser"],"https://kiwibrowser.com/","","b"),
E("Safari",["safari"],"https://www.apple.com/safari/","","b"),
E("UC Browser",["uc","uc browser"],"https://www.ucweb.com/","","b"),
E("Slimjet",["slimjet"],"https://www.slimjet.com/","","b"),
E("Comodo Dragon",["comodo dragon","dragon"],"https://www.comodo.com/home/browsers-toolbars/browser.php","","b"),
E("Naver Whale",["whale","naver whale"],"https://whale.naver.com/","","b"),
E("SRWare Iron",["iron","srware iron"],"https://www.srware.net/iron/","","b"),
E("IntelliJ IDEA Ultimate",["intellij ultimate","idea ultimate"],"https://www.jetbrains.com/idea/download/","","d"),
E("PyCharm Community",["pycharm","pycharm community"],"https://www.jetbrains.com/pycharm/download/","","d"),
E("PyCharm Professional",["pycharm pro","pycharm professional"],"https://www.jetbrains.com/pycharm/download/","","d"),
E("WebStorm",["webstorm"],"https://www.jetbrains.com/webstorm/download/","","d"),
E("GoLand",["goland"],"https://www.jetbrains.com/go/download/","","d"),
E("Android Studio",["android studio","androidstudio"],"https://developer.android.com/studio","","d"),
E("Eclipse IDE",["eclipse","eclipse ide"],"https://eclipseide.org/","","d"),
E("NetBeans",["netbeans","apache netbeans"],"https://netbeans.apache.org/","","d"),
E("CLion",["clion"],"https://www.jetbrains.com/clion/download/","","d"),
E("Rider",["rider","jetbrains rider"],"https://www.jetbrains.com/rider/download/","","d"),
E("RubyMine",["rubymine"],"https://www.jetbrains.com/ruby/download/","","d"),
E("PhpStorm",["phpstorm"],"https://www.jetbrains.com/phpstorm/download/","","d"),
E("VS 2022 Community",["vs2022 community","vs community"],"https://visualstudio.microsoft.com/vs/community/","","d"),
E("VS 2022 Professional",["vs2022 pro","vs professional"],"https://visualstudio.microsoft.com/vs/professional/","","d"),
E("VS 2022 Enterprise",["vs2022 enterprise","vs enterprise"],"https://visualstudio.microsoft.com/vs/enterprise/","","d"),
E("Visual Studio 2019",["vs2019"],"https://visualstudio.microsoft.com/vs/older-downloads/","","d"),
E("VS Code Insiders",["vscode insiders","code insiders"],"https://code.visualstudio.com/insiders/","","d"),
E("Atom",["atom"],"https://atom-editor.cc/","","d"),
E("Vim",["vim","gvim"],"https://www.vim.org/download.php","","d"),
E("NeoVim",["neovim","nvim"],"https://neovim.io/","","d"),
E("Emacs",["emacs","gnu emacs"],"https://www.gnu.org/software/emacs/","","d"),
E("GitHub Desktop",["github desktop","githubdesktop"],"https://desktop.github.com/","","d"),
E("SourceTree",["sourcetree","atlassian sourcetree"],"https://www.sourcetreeapp.com/","","d"),
E("GitKraken",["gitkraken"],"https://www.gitkraken.com/","","d"),
E("Insomnia",["insomnia"],"https://insomnia.rest/download","","d"),
E("Jupyter",["jupyter","jupyter notebook"],"https://jupyter.org/","","d"),
E("Anaconda",["anaconda"],"https://www.anaconda.com/download","","d"),
E("CMake",["cmake"],"https://cmake.org/download/","","d"),
E("Gradle",["gradle"],"https://gradle.org/install/","","d"),
E("Maven",["maven","apache maven"],"https://maven.apache.org/download.cgi","","d"),
E("Vagrant",["vagrant","hashicorp vagrant"],"https://www.vagrantup.com/downloads","","d"),
E("VirtualBox",["virtualbox","oracle vm virtualbox"],"https://www.virtualbox.org/wiki/Downloads","","d"),
E("VMware Workstation Pro",["vmware","vmware workstation"],"https://www.vmware.com/products/workstation-pro.html","","d"),
E("WSL",["wsl","wsl2","windows subsystem for linux"],"https://learn.microsoft.com/en-us/windows/wsl/","","d"),
E("yarn",["yarn","yarnpkg"],"https://yarnpkg.com/","","d"),
E("pnpm",["pnpm"],"https://pnpm.io/installation","","d"),
E("bun",["bun"],"https://bun.sh/","","d"),
E("Deno",["deno"],"https://deno.land/","","d"),
E("Kubernetes",["kubernetes","k8s"],"https://kubernetes.io/","","d"),
E("Minikube",["minikube"],"https://minikube.sigs.k8s.io/docs/","","d"),
E("Helm",["helm"],"https://helm.sh/","","d"),
E("Terraform",["terraform","hashicorp terraform"],"https://www.terraform.io/downloads","","d"),
E("Ansible",["ansible"],"https://www.ansible.com/","","d"),
E("Jenkins",["jenkins"],"https://www.jenkins.io/download/","","d"),
E("TeamCity",["teamcity","jetbrains teamcity"],"https://www.jetbrains.com/teamcity/download/","","d"),
E("Octopus Deploy",["octopus deploy","octopus"],"https://octopus.com/downloads","","d"),
E("FileZilla",["filezilla"],"https://filezilla-project.org/","","d"),
E("WinSCP",["winscp"],"https://winscp.net/","","d"),
E("PuTTY",["putty"],"https://www.putty.org/","","d"),
E("OpenSSH",["openssh","ssh"],"https://www.openssh.com/","","d"),
E("Wireshark",["wireshark"],"https://www.wireshark.org/download.html","","d"),
E("Fiddler Everywhere",["fiddler","fiddler everywhere"],"https://www.telerik.com/download/fiddler-everywhere","","d"),
E("Charles Proxy",["charles proxy","charles"],"https://www.charlesproxy.com/download/","","d"),
E("curl",["curl"],"https://curl.se/windows/","","d"),
E("wget",["wget","gnu wget"],"https://eternallybored.org/misc/wget/","","d"),
E("TortoiseGit",["tortoisegit"],"https://tortoisegit.org/","","d"),
E("TortoiseSVN",["tortoisesvn"],"https://tortoisesvn.net/","","d"),
E("Make",["make","gnu make"],"https://www.gnu.org/software/make/","","d"),
E("Redis Insight",["redis insight","redisinsight"],"https://redis.com/redis-enterprise/redis-insight/","","d"),
E("Azure Data Studio",["azure data studio","ads"],"https://learn.microsoft.com/en-us/azure-data-studio/download","","d"),
E("Oracle JDK",["oracle jdk","oracle java"],"https://www.oracle.com/java/technologies/downloads/","","r"),
E("Java JRE",["jre","java runtime"],"https://www.java.com/download/","","r"),
E("Rust",["rust","rustc"],"https://www.rust-lang.org/tools/install","","r"),
E(".NET SDK",["dotnet","dotnet sdk",".net sdk"],"https://dotnet.microsoft.com/download","","r"),
E(".NET Runtime",[".net runtime","dotnet runtime"],"https://dotnet.microsoft.com/en-us/download/dotnet","","r"),
E(".NET Framework 4.8",["dotnet framework",".net framework"],"https://dotnet.microsoft.com/en-us/download/dotnet-framework","","r"),
E("Ruby",["ruby"],"https://rubyinstaller.org/","","r"),
E("PHP",["php"],"https://windows.php.net/download/","","r"),
E("Perl",["perl","strawberry perl"],"https://strawberryperl.com/","","r"),
E("Lua",["lua"],"https://lua.org/","","r"),
E("R Language",["r","r language"],"https://cran.r-project.org/bin/windows/base/","","r"),
E("Julia",["julia"],"https://julialang.org/downloads/","","r"),
E("Erlang",["erlang"],"https://www.erlang.org/downloads","","r"),
E("Elixir",["elixir"],"https://elixir-lang.org/install.html","","r"),
E("Haskell",["haskell","ghc"],"https://www.haskell.org/downloads/","","r"),
E("Scala",["scala"],"https://www.scala-lang.org/download/","","r"),
E("Kotlin",["kotlin"],"https://kotlinlang.org/","","r"),
E("Dart",["dart"],"https://dart.dev/get-dart","","r"),
E("Flutter",["flutter"],"https://docs.flutter.dev/get-started/install/windows","","r"),
E("CUDA Toolkit",["cuda","nvidia cuda"],"https://developer.nvidia.com/cuda-downloads","","r"),
E("PowerShell 7",["powershell","pwsh"],"https://learn.microsoft.com/en-us/powershell/","","r"),
E("MinGW-w64",["mingw","mingw-w64"],"https://www.mingw-w64.org/","","r"),
E("MSYS2",["msys2"],"https://www.msys2.org/","","r"),
E("LLVM/Clang",["clang","llvm"],"https://releases.llvm.org/","","r"),
E("MySQL",["mysql server","mysql community"],"https://dev.mysql.com/downloads/mysql/","","D"),
E("pgAdmin",["pgadmin","pgadmin4"],"https://www.pgadmin.org/download/","","D"),
E("Navicat Premium",["navicat","navicat premium"],"https://www.navicat.com/en/download/navicat-premium","","D"),
E("SQLite",["sqlite"],"https://www.sqlite.org/download.html","","D"),
E("SQLiteStudio",["sqlitestudio"],"https://sqlitestudio.pl/","","D"),
E("SQL Server",["sql server","mssql"],"https://www.microsoft.com/en-us/sql-server/sql-server-downloads","","D"),
E("SSMS",["ssms","sql server management studio"],"https://learn.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms","","D"),
E("Oracle Database",["oracle db","oracle database"],"https://www.oracle.com/database/technologies/","","D"),
E("Oracle SQL Developer",["oracle sql developer","sqldeveloper"],"https://www.oracle.com/database/sqldeveloper/","","D"),
E("MongoDB Community Server",["mongodb","mongo"],"https://www.mongodb.com/try/download/community","","D"),
E("MongoDB Compass",["mongodb compass"],"https://www.mongodb.com/products/compass","","D"),
E("Redis",["redis"],"https://redis.io/download/","","D"),
E("Redis Desktop Manager",["rdm","redis desktop manager"],"https://redisdesktop.com/","","D"),
E("Memurai",["memurai"],"https://www.memurai.com/","","D"),
E("Cassandra",["cassandra"],"https://cassandra.apache.org/","","D"),
E("Neo4j Desktop",["neo4j"],"https://neo4j.com/download/","","D"),
E("CouchDB",["couchdb"],"https://couchdb.apache.org/","","D"),
E("MariaDB",["mariadb"],"https://mariadb.org/download/","","D"),
E("Firebird",["firebird"],"https://firebirdsql.org/","","D"),
E("Supabase CLI",["supabase"],"https://supabase.com/docs/guides/cli","","D"),
E("DbVisualizer",["dbvisualizer"],"https://www.dbvis.com/download/","","D"),
E("TablePlus",["tableplus"],"https://tableplus.com/download","","D"),
E("Adobe Photoshop",["photoshop","ps","adobe photoshop"],"https://www.adobe.com/products/photoshop.html","","g"),
E("Adobe Illustrator",["illustrator","ai"],"https://www.adobe.com/products/illustrator.html","","g"),
E("Adobe InDesign",["indesign"],"https://www.adobe.com/products/indesign.html","","g"),
E("Adobe After Effects",["after effects","ae"],"https://www.adobe.com/products/aftereffects.html","","g"),
E("Adobe Premiere Pro",["premiere pro","premiere"],"https://www.adobe.com/products/premiere.html","","g"),
E("Adobe Lightroom",["lightroom"],"https://www.adobe.com/products/photoshop-lightroom.html","","g"),
E("Sketch",["sketch"],"https://www.sketch.com/","","g"),
E("Krita",["krita"],"https://krita.org/en/download/","","g"),
E("Paint.NET",["paint.net","paintnet"],"https://www.getpaint.net/","","g"),
E("Affinity Photo",["affinity photo"],"https://affinity.serif.com/en-us/photo/","","g"),
E("Affinity Designer",["affinity designer"],"https://affinity.serif.com/en-us/designer/","","g"),
E("CorelDraw",["coreldraw"],"https://www.coreldraw.com/","","g"),
E("AutoCAD",["autocad"],"https://www.autodesk.com/products/autocad/","","g"),
E("Fusion 360",["fusion 360","fusion360"],"https://www.autodesk.com/products/fusion-360/","","g"),
E("SolidWorks",["solidworks"],"https://www.solidworks.com/","","g"),
E("FreeCAD",["freecad"],"https://www.freecad.org/downloads.php","","g"),
E("DaVinci Resolve",["davinci resolve","davinci"],"https://www.blackmagicdesign.com/products/davinciresolve/","","g"),
E("Canva",["canva"],"https://www.canva.com/download/","","g"),
E("Aseprite",["aseprite"],"https://www.aseprite.org/","","g"),
E("Maya",["maya","autodesk maya"],"https://www.autodesk.com/products/maya/","","g"),
E("3ds Max",["3ds max","3d max"],"https://www.autodesk.com/products/3ds-max/","","g"),
E("Cinema 4D",["cinema 4d","c4d"],"https://www.maxon.net/en/cinema-4d","","g"),
E("ZBrush",["zbrush"],"https://www.maxon.net/en/zbrush","","g"),
E("Procreate",["procreate"],"https://procreate.com/","","g"),
E("WeChat",["wechat","weixin"],"https://pc.weixin.qq.com/","","c"),
E("QQ",["qq"],"https://im.qq.com/pcqq/","","c"),
E("TIM",["tim"],"https://office.qq.com/","","c"),
E("Microsoft Teams",["teams","microsoft teams"],"https://www.microsoft.com/en-us/microsoft-teams/download-app","","c"),
E("DingTalk",["dingtalk","dingding"],"https://www.dingtalk.com/en","","c"),
E("Feishu",["feishu","lark"],"https://www.feishu.cn/download","","c"),
E("WhatsApp",["whatsapp"],"https://www.whatsapp.com/download","","c"),
E("Skype",["skype"],"https://www.skype.com/en/get-skype/","","c"),
E("Signal",["signal"],"https://signal.org/download/","","c"),
E("Viber",["viber"],"https://www.viber.com/download/","","c"),
E("Line",["line"],"https://line.me/en-US/download","","c"),
E("KakaoTalk",["kakaotalk"],"https://www.kakaocorp.com/page/service/service/KakaoTalk","","c"),
E("Messenger",["messenger"],"https://www.messenger.com/desktop","","c"),
E("Element",["element","matrix"],"https://element.io/download","","c"),
E("HexChat",["hexchat","irc"],"https://hexchat.github.io/","","c"),
E("Trello",["trello"],"https://trello.com/platforms","","c"),
E("Asana",["asana"],"https://asana.com/download","","c"),
E("Notion",["notion"],"https://www.notion.so/desktop","","c"),
E("Twist",["twist"],"https://twist.com/download","","c"),
E("Mattermost",["mattermost"],"https://mattermost.com/download/","","c"),
E("Rocket.Chat",["rocket.chat","rocketchat"],"https://www.rocket.chat/download","","c"),
E("Google Meet",["google meet"],"https://meet.google.com/","","c"),
E("Cisco Webex",["webex","cisco webex"],"https://www.webex.com/downloads.html","","c"),
E("Zoho Cliq",["zoho cliq","cliq"],"https://www.zoho.com/cliq/download/","","c"),
E("Tencent Meeting",["tencent meeting","voov meeting"],"https://voovmeeting.com/download-center.html","","c"),
E("MPC-HC",["mpc-hc","mpc hc"],"https://mpc-hc.org/","","m"),
E("MPC-BE",["mpc-be","mpc be"],"https://mpcbe.sourceforge.io/","","m"),
E("KMPlayer",["kmplayer"],"https://www.kmplayer.com/","","m"),
E("GOM Player",["gom player"],"https://www.gomlab.com/gomplayer-media-player/","","m"),
E("foobar2000",["foobar2000","foobar"],"https://www.foobar2000.org/download","","m"),
E("AIMP",["aimp"],"https://www.aimp.ru/","","m"),
E("MusicBee",["musicbee"],"https://getmusicbee.com/","","m"),
E("XSplit",["xsplit"],"https://www.xsplit.com/download","","m"),
E("Streamlabs Desktop",["streamlabs"],"https://streamlabs.com/","","m"),
E("Bandicam",["bandicam"],"https://www.bandicam.com/downloads/","","m"),
E("Audacity",["audacity"],"https://www.audacityteam.org/download/","","m"),
E("Adobe Audition",["audition","adobe audition"],"https://www.adobe.com/products/audition.html","","m"),
E("Cubase",["cubase"],"https://www.steinberg.net/cubase/","","m"),
E("FL Studio",["fl studio"],"https://www.image-line.com/fl-studio-download/","","m"),
E("Ableton Live",["ableton live"],"https://www.ableton.com/en/live/","","m"),
E("HandBrake",["handbrake"],"https://handbrake.fr/downloads.php","","m"),
E("FFmpeg",["ffmpeg"],"https://ffmpeg.org/download.html","","m"),
E("LosslessCut",["losslesscut"],"https://github.com/mifi/lossless-cut","","m"),
E("Shotcut",["shotcut"],"https://shotcut.org/download/","","m"),
E("Kdenlive",["kdenlive"],"https://kdenlive.org/en/download/","","m"),
E("OpenShot",["openshot"],"https://www.openshot.org/download/","","m"),
E("mpv",["mpv"],"https://mpv.io/installation/","","m"),
E("SMPlayer",["smplayer"],"https://www.smplayer.info/downloads/","","m"),
E("VSDC Video Editor",["vsdc"],"https://www.videosoftdev.com/free-video-editor","","m"),
E("Ocenaudio",["ocenaudio"],"https://www.ocenaudio.com/en/download","","m"),
E("REAPER",["reaper"],"https://www.reaper.fm/download.php","","m"),
E("LMMS",["lmms"],"https://lmms.io/download/","","m"),
E("360 Total Security",["360 total security"],"https://www.360totalsecurity.com/","","s"),
E("360 Antivirus",["360 antivirus"],"https://www.360totalsecurity.com/en/antivirus/","","s"),
E("Huorong",["huorong"],"https://www.huorong.cn/","","s"),
E("ESET NOD32",["eset","nod32"],"https://www.eset.com/us/home/antivirus/","","s"),
E("Avast",["avast"],"https://www.avast.com/download-antivirus","","s"),
E("AVG",["avg"],"https://www.avg.com/en-us/download-antivirus","","s"),
E("Avira",["avira"],"https://www.avira.com/en/download-free-antivirus","","s"),
E("Norton",["norton"],"https://www.norton.com/downloads","","s"),
E("McAfee",["mcafee"],"https://www.mcafee.com/downloads/antivirus.aspx","","s"),
E("Comodo Antivirus",["comodo"],"https://www.comodo.com/home/download/download.php","","s"),
E("ZoneAlarm",["zonealarm"],"https://www.zonealarm.com/software/firewall/","","s"),
E("GlassWire",["glasswire"],"https://www.glasswire.com/download/","","s"),
E("WireGuard",["wireguard"],"https://www.wireguard.com/install/","","s"),
E("OpenVPN",["openvpn"],"https://openvpn.net/download-open-vpn/","","s"),
E("ProtonVPN",["protonvpn"],"https://protonvpn.com/download/","","s"),
E("Cloudflare WARP",["cloudflare warp","warp"],"https://1.1.1.1/","","s"),
E("1Password",["1password"],"https://1password.com/downloads/windows/","","s"),
E("Bitwarden",["bitwarden"],"https://bitwarden.com/download/","","s"),
E("KeePass",["keepass"],"https://keepass.info/download.html","","s"),
E("KeePassXC",["keepassxc"],"https://keepassxc.org/download/","","s"),
E("VeraCrypt",["veracrypt"],"https://www.veracrypt.fr/en/Downloads.html","","s"),
E("NordVPN",["nordvpn"],"https://nordvpn.com/download/","","s"),
E("ExpressVPN",["expressvpn"],"https://www.expressvpn.com/download","","s"),
E("AdGuard",["adguard"],"https://adguard.com/en/download.html","","s"),
E("uBlock Origin",["ublock origin","ublock"],"https://ublockorigin.com/","","s"),
E("WinRAR",["winrar","rar"],"https://www.win-rar.com/download.html","","u"),
E("Bandizip",["bandizip"],"https://www.bandisoft.com/bandizip/","","u"),
E("PeaZip",["peazip"],"https://peazip.github.io/","","u"),
E("Snipaste",["snipaste"],"https://www.snipaste.com/","","u"),
E("Greenshot",["greenshot"],"https://getgreenshot.org/download/","","u"),
E("Lightshot",["lightshot"],"https://app.prntscr.com/en/download.html","","u"),
E("PicPick",["picpick"],"https://picpick.app/en/download","","u"),
E("FastStone Capture",["faststone capture"],"https://www.faststone.org/FSCaptureDownload.htm","","u"),
E("Flameshot",["flameshot"],"https://flameshot.org/","","u"),
E("GPU-Z",["gpuz","gpu-z"],"https://www.techpowerup.com/gpuz/","","u"),
E("HWMonitor",["hwmonitor"],"https://www.cpuid.com/softwares/hwmonitor.html","","u"),
E("HWiNFO",["hwinfo"],"https://www.hwinfo.com/download/","","u"),
E("Speccy",["speccy"],"https://www.ccleaner.com/speccy/download/","","u"),
E("CrystalDiskInfo",["crystaldiskinfo"],"https://crystalmark.info/en/download/","","u"),
E("CrystalDiskMark",["crystaldiskmark"],"https://crystalmark.info/en/download/","","u"),
E("AIDA64",["aida64"],"https://www.aida64.com/downloads","","u"),
E("FurMark",["furmark"],"https://geeks3d.com/furmark/","","u"),
E("MSI Afterburner",["msi afterburner","afterburner"],"https://www.msi.com/Landing/afterburner/graphics-cards","","u"),
E("CCleaner",["ccleaner"],"https://www.ccleaner.com/ccleaner/download/","","u"),
E("Glary Utilities",["glary utilities"],"https://www.glarysoft.com/glary-utilities/","","u"),
E("Wise Care 365",["wise care 365"],"https://www.wisecleaner.com/wise-care-365.html","","u"),
E("Defraggler",["defraggler"],"https://www.ccleaner.com/defraggler/download/","","u"),
E("Recuva",["recuva"],"https://www.ccleaner.com/recuva/download/","","u"),
E("EaseUS Data Recovery",["easeus"],"https://www.easeus.com/datarecoverywizard/","","u"),
E("AOMEI Backupper",["aomei"],"https://www.aomeitech.com/aomei-backupper.html","","u"),
E("Rufus",["rufus"],"https://rufus.ie/en/","","u"),
E("BalenaEtcher",["balenaetcher","etcher"],"https://www.balena.io/etcher/","","u"),
E("Ventoy",["ventoy"],"https://www.ventoy.net/en/download.html","","u"),
E("WinToUSB",["wintousb"],"https://www.easyuefi.com/wintousb/","","u"),
E("HxD Hex Editor",["hxd","hex editor"],"https://mh-nexus.de/en/hxd/","","u"),
E("Beyond Compare",["beyond compare"],"https://www.scootersoftware.com/download","","u"),
E("WinMerge",["winmerge"],"https://winmerge.org/downloads/","","u"),
E("Meld",["meld"],"https://meldmerge.org/","","u"),
E("TreeSize Free",["treesize"],"https://www.jam-software.com/treesize_free","","u"),
E("WizTree",["wiztree"],"https://diskanalyzer.com/","","u"),
E("SpaceSniffer",["spacesniffer"],"http://www.uderzo.it/main_products/space_sniffer/","","u"),
E("WinDirStat",["windirstat"],"https://windirstat.net/","","u"),
E("LockHunter",["lockhunter"],"https://lockhunter.com/","","u"),
E("Process Explorer",["process explorer","procexp"],"https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer","","u"),
E("Autoruns",["autoruns"],"https://learn.microsoft.com/en-us/sysinternals/downloads/autoruns","","u"),
E("Sysinternals Suite",["sysinternals"],"https://learn.microsoft.com/en-us/sysinternals/downloads/sysinternals-suite","","u"),
E("ConEmu",["conemu"],"https://conemu.github.io/","","u"),
E("Cmder",["cmder"],"https://cmder.app/","","u"),
E("Alacritty",["alacritty"],"https://alacritty.org/","","u"),
E("Flow Launcher",["flow launcher"],"https://www.flowlauncher.com/","","u"),
E("Listary",["listary"],"https://www.listary.com/","","u"),
E("Wox",["wox"],"https://github.com/Wox-launcher/Wox","","u"),
E("Keypirinha",["keypirinha"],"https://keypirinha.com/","","u"),
E("Dism++",["dism++","dismpp"],"https://github.com/Chuyu-Team/Dism-Multi-language","","u"),
E("Geek Uninstaller",["geek uninstaller"],"https://geekuninstaller.com/","","u"),
E("Revo Uninstaller",["revo uninstaller"],"https://www.revouninstaller.com/","","u"),
E("IObit Uninstaller",["iobit uninstaller"],"https://www.iobit.com/en/advanceduninstaller.php","","u"),
E("Notepad3",["notepad3"],"https://github.com/rizonesoft/Notepad3","","u"),
E("TeraCopy",["teracopy"],"https://www.codesector.com/teracopy","","u"),
E("qBittorrent",["qbittorrent"],"https://www.qbittorrent.org/","","u"),
E("Internet Download Manager",["idm","internet download manager"],"https://www.internetdownloadmanager.com/","","u"),
E("Duplicate Cleaner",["duplicate cleaner"],"https://www.digitalvolcano.co.uk/duplicatecleaner.html","","u"),
E("Macrium Reflect",["macrium reflect"],"https://www.macrium.com/reflectfree","","u"),
E("Microsoft Office 2021",["office 2021","microsoft office 2021"],"https://www.microsoft.com/en-us/microsoft-365","","p"),
E("Office 365",["office 365","microsoft 365"],"https://www.microsoft.com/en-us/microsoft-365","","p"),
E("OpenOffice",["openoffice","apache openoffice"],"https://www.openoffice.org/download/","","p"),
E("Foxit Reader",["foxit","foxit reader"],"https://www.foxit.com/pdf-reader/","","p"),
E("Adobe Acrobat Reader",["acrobat reader","adobe reader"],"https://get.adobe.com/reader/","","p"),
E("Sumatra PDF",["sumatra pdf","sumatra"],"https://www.sumatrapdfreader.org/download-free-pdf-viewer","","p"),
E("Nitro PDF Reader",["nitro pdf","nitro"],"https://www.gonitro.com/pdf-reader/download","","p"),
E("PDF24 Creator",["pdf24","pdf24 creator"],"https://tools.pdf24.org/en/creator","","p"),
E("Obsidian",["obsidian"],"https://obsidian.md/download","","p"),
E("OneNote",["onenote"],"https://www.onenote.com/download","","p"),
E("Evernote",["evernote"],"https://evernote.com/download","","p"),
E("Joplin",["joplin"],"https://joplinapp.org/","","p"),
E("Standard Notes",["standard notes"],"https://standardnotes.com/","","p"),
E("Todoist",["todoist"],"https://todoist.com/downloads","","p"),
E("Microsoft To Do",["microsoft to do","ms todo"],"https://todo.microsoft.com/tasks/","","p"),
E("TickTick",["ticktick"],"https://ticktick.com/download","","p"),
E("Monday.com",["monday.com","monday"],"https://monday.com/","","p"),
E("XMind",["xmind"],"https://xmind.app/download/","","p"),
E("Zotero",["zotero"],"https://www.zotero.org/download/","","p"),
E("Calibre",["calibre"],"https://calibre-ebook.com/download","","p"),
E("Draw.io",["draw.io","diagrams.net"],"https://www.diagrams.net/","","p"),
E("ClickUp",["clickup"],"https://clickup.com/download","","p"),
E("Zoho Notebook",["zoho notebook"],"https://www.zoho.com/notebook/download/","","p"),
E("Steam",["steam"],"https://store.steampowered.com/","https://cdn.cloudflare.steamstatic.com/client/installer/SteamSetup.exe","G"),
E("Epic Games Launcher",["epic games","epic"],"https://store.epicgames.com/","","G"),
E("EA App",["ea app","origin","ea"],"https://www.ea.com/ea-app","","G"),
E("Ubisoft Connect",["ubisoft connect","uplay"],"https://ubisoftconnect.com/","","G"),
E("GOG Galaxy",["gog galaxy","gog"],"https://www.gog.com/galaxy","","G"),
E("Battle.net",["battle.net","blizzard"],"https://www.blizzard.com/download/","","G"),
E("Xbox App",["xbox","xbox app"],"https://www.xbox.com/en-US/apps/xbox-app-for-pc","","G"),
E("Itch.io",["itch.io","itch"],"https://itch.io/app","","G"),
E("Minecraft Launcher",["minecraft"],"https://www.minecraft.net/en-us/download","","G"),
E("Riot Client",["riot client","league of legends","valorant"],"https://riotgames.com/","","G"),
E("WeGame",["wegame"],"https://www.wegame.com.cn/","","G"),
E("NetEase Games",["netease games","netease"],"https://game.163.com/","","G"),
E("PlayStation Plus",["playstation plus","ps plus"],"https://www.playstation.com/ps-plus/","","G"),
E("Rockstar Games Launcher",["rockstar","rockstar games"],"https://socialclub.rockstargames.com/","","G"),
E("Parsec",["parsec"],"https://parsec.app/downloads","","G"),
E("Google Drive",["google drive","gdrive"],"https://www.google.com/drive/download/","","o"),
E("Dropbox",["dropbox"],"https://www.dropbox.com/install","","o"),
E("OneDrive",["onedrive","microsoft onedrive"],"https://www.microsoft.com/en-us/microsoft-365/onedrive","","o"),
E("TeamViewer",["teamviewer"],"https://www.teamviewer.com/en/download/","","o"),
E("AnyDesk",["anydesk"],"https://anydesk.com/en/downloads/windows","","o"),
E("RustDesk",["rustdesk"],"https://rustdesk.com/","","o"),
E("VMware Horizon Client",["vmware horizon","horizon client"],"https://customerconnect.vmware.com/en/downloads/","","o"),
E("Cisco AnyConnect",["anyconnect","cisco anyconnect"],"https://www.cisco.com/c/en/us/products/security/anyconnect-secure-mobility-client/","","o"),
E("FortiClient",["forticlient","fortinet"],"https://www.fortinet.com/support/product-downloads","","o"),
E("Google Earth",["google earth"],"https://www.google.com/earth/about/versions/","","o"),
E("Microsoft Power BI",["power bi","microsoft power bi"],"https://powerbi.microsoft.com/en-us/downloads/","","o"),
E("Tableau Desktop",["tableau","tableau desktop"],"https://www.tableau.com/products/desktop/download","","o"),
E("MATLAB",["matlab"],"https://www.mathworks.com/downloads/","","o"),
E("OriginPro",["origin","originlab"],"https://www.originlab.com/","","o"),
E("SketchUp",["sketchup"],"https://www.sketchup.com/","","o"),
E("Baidu Netdisk",["baidu netdisk","baidupan"],"https://pan.baidu.com/download/","","o"),
E("Aliyun Drive",["aliyundrive","aliyun drive"],"https://www.aliyundrive.com/download","","o"),
E("XnView",["xnview"],"https://www.xnview.com/en/xnviewmp/","","o"),
E("IrfanView",["irfanview"],"https://www.irfanview.com/","","o"),
E("Honeyview",["honeyview"],"https://www.bandisoft.com/honeyview/","","o"),
E("Thunder",["thunder","xunlei"],"https://www.xunlei.com/","","o"),
E("Sunlogin",["sunlogin","sunflower"],"https://sunlogin.oray.com/download/","","o"),
E("Baidu IME",["baidu ime","baidu input method"],"https://shurufa.baidu.com/","","o"),
E("Sogou IME",["sogou ime","sogou input method"],"https://pinyin.sogou.com/","","o"),
E("AutoDesk Revit",["revit","autodesk revit"],"https://www.autodesk.com/products/revit/","","o"),
E("WinPcap",["winpcap"],"https://www.winpcap.org/","","o"),
E("Npcap",["npcap"],"https://npcap.com/","","o"),
]);
// Fix office -> productivity
for (const e of entries) {
  if (e.category === "office") e.category = "productivity";
}

// Deduplicate by name (keep first occurrence)
const seen2 = new Set();
const deduped = [];
for (const e of entries) {
  if (!seen2.has(e.software_name)) {
    seen2.add(e.software_name);
    deduped.push(e);
  }
}

deduped.sort((a, b) => a.category.localeCompare(b.category) || a.software_name.localeCompare(b.software_name));
fs.writeFileSync(f, JSON.stringify(deduped, null, 2), "utf-8");
console.log("Total entries:", deduped.length);
const cats = {};
deduped.forEach(e => { cats[e.category] = (cats[e.category] || 0) + 1; });
console.log("By category:", JSON.stringify(cats));
